name: build

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node: [ '10', '12' ]

    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
        env:
          ABUSEIPDB_TOKEN: ${{ secrets.ABUSEIPDB_TOKEN }}s
      - run: npm install
      - run: npm test
      - run: npm run build:skip-tests
