name: build

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '10', '12' ]

    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: npm install
      - name: Build
        run: npm run build:skip-tests
      - name: Test
        run: npm run test
      - name: Upload codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: umbress-codecov
          fail_ci_if_error: true
          yml: ../../codecov.yml