name: build

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    runs-on: ${{ matrix.node-version }}
    name: ${{ matrix.node-version }} tests
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Run tests
        env:
          ABUSEIPDB_TOKEN: ${{ secrets.ABUSEIPDB_TOKEN }}
        run: |
          npm install
          npm run build
          npm run test

  build:
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} w/ Node ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install and build
        run: |
          npm install
          npm run build:skip-tests
